zyzmoz/global-player

- .github/ISSUE_TEMPLATE/custom.md
[Ticket](https://trello.com/c/b8ih6NEi/18-configure-coding-practices)
Add the template to git settings
> documentation: Update issue templates

- backend/src/models/Plan.ts
- backend/src/routes.ts
> feature: Plan Routes

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
[Ticket](https://trello.com/c/b8ih6NEi/18-configure-coding-practices)
_Please remember that the reviewer may not be as familiar with the work being done or the project as you._
Create Issue and PR templates accordingly to the [last class](https://d2l.langara.bc.ca/d2l/le/content/244148/viewContent/3908801/View)
> documentation: issue and pr templates

- .github/workflows/blocking-issues.yml
[Ticket](https://trello.com/c/O3gOrurr/71-update-git-to-block-prs-depending-on-other-prs)
Configure git to block PRs depending on other PRs
> chore: Configure Git to block PRs that have dependencies 

- frontend/src/components/Button/Button.jsx
- frontend/src/components/Headline/Headline.jsx
> created button and headline component

- frontend/package-lock.json
- frontend/src/components/Header/Header.jsx
- frontend/src/components/Header/LandingPageNavMenu.jsx
- frontend/src/components/Image/Image.jsx
- frontend/src/sass/navigation/_header.scss
- frontend/src/sass/navigation/_navigation.scss
- frontend/src/sass/style.scss
- frontend/src/storybook/storybook.jsx
Created the Header and Image component.
> feature: Create Header and Image Component

- frontend/package-lock.json
- frontend/src/components/Button/Button.jsx
- frontend/src/components/Login/Login.jsx
- frontend/src/index.jsx
> created Login page

- frontend/src/components/SearchBar/SearchBar.jsx
> created searchbar component

- frontend/src/components/Card/Card.jsx
> created card component

- frontend/src/components/Avatar/Avatar.jsx
- frontend/src/components/Input/Input.jsx
- frontend/src/sass/base-elements/_avatar.scss
- frontend/src/sass/base-elements/_index.scss
- frontend/src/sass/style.scss
- frontend/src/storybook/storybook.jsx
[Ticket](https://trello.com/c/ERzcT3Gw/74-create-avatar-component)
> feature: Create Avatar Component

- frontend/src/components/Slider/Slider.jsx
> created slider component

- frontend/src/components/ProfilePopUp/ProfilePopUp.jsx
Created the user profile popup, missing only the logic behind log out.
> feature: Profile PopUp

- frontend/src/components/Sidebar/Sidebar.jsx
- frontend/src/sass/accessibility/_visually-hidden.scss
- frontend/src/sass/navigation/_sidebar.scss
- frontend/src/sass/style.scss
[Ticket](https://trello.com/c/eWbkvqHB/76-create-sidebar-component)
```
npm run
```
1. 
2.
---
> feature: Create Sidebar Component

- frontend/src/components/Tag/Tag.jsx
- frontend/src/storybook/storybook.jsx
> feature: Tag Component

- frontend/src/components/ProgressBar/ProgressBar.jsx
- frontend/src/sass/style.scss
> feature: Create ProgressBar Component

- frontend/src/components/Modal/Modal.jsx
- frontend/src/sass/base-elements/_index.scss
- frontend/src/sass/base-elements/_modal.scss
> feature: Modal Component

- frontend/package-lock.json
- frontend/src/components/DoughnutChart/DoughnutChart.jsx
- frontend/src/storybook/storybook.jsx
[Ticket](https://trello.com/c/BOlUBOj8/86-create-doughnutchart-component)
```
npm run
```
1. 
2.
---
> feature: Create DoughnutChart Component

- frontend/src/components/Accordion/Accordion.jsx
- frontend/src/sass/site-layout/_index.scss
- frontend/src/storybook/storybook.jsx
[Ticket](https://github.com/zyzmoz/global-player/issues/46)
> Accordion component
```
npm run
```
1. 
2.
---
> Accordion component

- frontend/src/components/Toast/Toast.jsx
- frontend/src/sass/base-elements/_button.scss
- frontend/src/sass/site-layout/_index.scss
- frontend/src/storybook/storybook.jsx
[Ticket](https://github.com/zyzmoz/global-player/issues/41)
> Toast component and part of its style. Some Props has been changed 
```
npm run
```
1. 
2.
---
> toast component

- frontend/src/components/Toast/Toast.jsx
- frontend/src/sass/base-elements/_button.scss
- frontend/src/sass/site-layout/_index.scss
- frontend/src/storybook/storybook.jsx
[Ticket](https://github.com/zyzmoz/global-player/issues/90)
> the style changes made to the component for some reason had not been sent before.
In this new commit the background color is corrected and other small details are modified.
```
npm run
```
1. 
2.
---
> Pr toast component 

- README.md
- backend/src/integrations/RiotAPI.ts
- backend/src/routes/index.ts
> feature: Riot API - Create getPlayer function

- backend/package-lock.json
- backend/src/integrations/RiotAPI.ts
- backend/src/routes/index.ts
- backend/src/shared/dbFunctions.ts
> feature: Riot API - Create getPuuid function

- backend/src/integrations/RiotAPI.ts
- backend/src/routes/index.ts
[Ticket](https://github.com/zyzmoz/global-player/issues/98)
```
npm run
```
1. 
2.
---
> feature: Riot API - Create getMatchDetails function

- backend/src/integrations/RiotAPI.ts
- backend/src/models/PlayerMatches.ts
- backend/src/routes/index.ts
- frontend/src/storybook/storybook.jsx
[Ticket](https://trello.com/c/xhtTbDrG/81-integration-with-riot-api)
```
npm run
```
1. 
2.
---
> feature: Create Riot API integration

- frontend/package-lock.json
- frontend/src/components/RadarChart/RadarChart.jsx
- frontend/src/sass/site-layout/_index.scss
- frontend/src/storybook/storybook.jsx
[Ticket](https://github.com/zyzmoz/global-player/issues/87)
> Radar Chart Component.
Point borders been included as I consider them important as a reference. However, this idea still needs to be discussed with designers.
```
npm run
```
1. 
2.
---
> Radar Chart Component

- backend/src/routes/analytics.ts
- backend/src/routes/index.ts
- backend/src/shared/dbFunctions.ts
- backend/src/shared/utils.ts
[Ticket](https://trello.com/c/f0bZpewy/93-create-endpoint-to-provide-dashboard-data)
A new endpoint was created to provide data used on the dashboard (TOP Players, ALL Players)
```
npm install \
npm run dev
```
---
> feature: Create Data Integration Functions

- frontend/src/components/DoughnutChart/DoughnutChart.jsx
- frontend/src/components/Header/RecruitersPagesNavMenu.jsx
- frontend/src/components/ProgressBar/ProgressBar.jsx
- frontend/src/components/Sidebar/Sidebar.jsx
- frontend/src/index.jsx
- frontend/src/pages/Login.jsx
- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/base-elements/_button.scss
- frontend/src/sass/base-elements/_progressbar.scss
- frontend/src/sass/navigation/_navigation.scss
- frontend/src/sass/navigation/_sidebar.scss
- frontend/src/sass/site-layout/_top-players-page.scss
- frontend/src/sass/style.scss
- frontend/src/sass/tables/_tables.scss
- frontend/src/sass/variables/_colors.scss
- frontend/src/storybook/storybook.jsx
> feature: Create Top Players Page (Dashboard)

- backend/src/routes/analytics.ts
- backend/src/shared/utils.ts
New endpoint `/api/v1/player/:id`
> feature: Create an endpoint to get analytical data about one player

- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/sass/site-layout/_player-details-page.scss
[Ticket](https://github.com/zyzmoz/global-player/issues/120)
[Ticket](https://trello.com/c/dz0DfCCo/97-integrate-player-details-to-backend)
> Integration of player details
```
npm run
```
1. 
2.
---
> feature: Integrate player details to backend

- frontend/src/components/Table/TableItem.jsx
- frontend/src/context/PlayerContext.jsx
- frontend/src/index.jsx
- frontend/src/pages/Login.jsx
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/pages/TopPlayersPage.jsx
Added Context to hold data about players selected and players to be compared
```
npm run
```
1. 
2.
---
> feature: Create state management to handle players' comparison

- frontend/src/index.jsx
- frontend/src/pages/ComparisonPage.jsx
- frontend/src/sass/site-layout/_comparison-page.scss
- frontend/src/sass/style.scss
> feature: Create Comparison Page

- backend/src/models/Review.ts
- backend/src/routes/analytics.ts
- backend/src/routes/license.ts
- backend/src/routes/plan.ts
- backend/src/routes/player.ts
- backend/src/routes/playerMatch.ts
- backend/src/routes/review.ts
- backend/src/routes/user.ts
- backend/src/shared/utils.ts
- frontend/src/components/Button/Button.jsx
- frontend/src/components/Slider/Slider.jsx
- frontend/src/context/PlayerContext.jsx
- frontend/src/index.jsx
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/pages/PlayerReviewOverview.jsx
- frontend/src/pages/ReviewPlayer.jsx
- frontend/src/sass/base-elements/_button.scss
- frontend/src/sass/base-elements/_index.scss
- frontend/src/sass/base-elements/_slider.scss
- frontend/src/sass/site-layout/_index.scss
- frontend/src/sass/site-layout/_player-review.scss
- frontend/src/sass/style.scss
[Ticket](https://trello.com/c/K2KSi9Z2/98-create-review-page)
Created a form to submit reviews and frontend integration to retrieve data from the backend
> feature: Create Player Review Page

- frontend/src/index.jsx
- frontend/src/pages/ComparisonResultsPage.jsx
- frontend/src/sass/site-layout/_comparison-results-page.scss
- frontend/src/sass/style.scss
> feature: Comparison Results Page

- frontend/src/context/PlayerContext.jsx
- frontend/src/pages/ComparisonResultsPage.jsx
> feature: Integrate Comparison Results to Backend

- frontend/src/pages/PlayerComparisonSelectPage.jsx
[Ticket](https://trello.com/c/pmUMOE4C/100-integrate-player-comparison-select-page-to-backend)
> Integration in progress
```
npm run
```
1. 
2.
---
> feature: Integrate Player Comparison Select Page to Backend IN PROGRESS

- frontend/src/pages/Login.jsx
- frontend/src/sass/site-layout/_login-page.scss
- frontend/src/sass/style.scss
> feature: Create Login Page

- backend/src/routes/analytics.ts
- frontend/src/pages/PlayerComparisonSelectPage.jsx
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/site-layout/_top-players-page.scss
> bug: fix backend functions where we use id as a parameter

- frontend/src/components/Card/Card.jsx
- frontend/src/pages/ComparisonPage.jsx
- frontend/src/sass/site-layout/_comparison-page.scss
[Ticket](https://trello.com/c/BEGkE5mt/101-feature-style-comparison-page)
```
npm run
```
1. 
2.
---
> feature: Style Comparison Page

- backend/src/routes/analytics.ts
- backend/src/routes/auth.ts
- backend/src/shared/utils.ts
- frontend/src/components/ProgressBar/ProgressBar.jsx
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/base-elements/_doughnut-chart.scss
- frontend/src/sass/site-layout/_player-details-page.scss
> bug: Player details page - Add missing content to cards

- backend/src/shared/utils.ts
> bug: Get Matches Function

- frontend/src/pages/ComparisonResultsPage.jsx
[Ticket](https://trello.com/c/9WREs8Yk/108-fix-comparison-results)
> Comparison results page fixed it
---
> fix: comparison results

- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/site-layout/_top-players-page.scss
> feature update top players dashboard

- frontend/src/components/Sidebar/Sidebar.jsx
- frontend/src/pages/ComparisonPage.jsx
> feature: Update Sidebar Link

- frontend/src/pages/ComparisonResultsPage.jsx
- frontend/src/pages/PlayerComparisonSelectPage.jsx
- frontend/src/sass/site-layout/_player-comparison-select-page.scss
[Ticket](https://trello.com/c/1gzB9BK7/109-show-more-players-to-compare-and-border-radius-button-in-select-player-page)
> Show more players to compare and border radius of the "+ VS" button has been fixed.
Active button is still missing.
```
npm run
```
1. 
2.
---
> fix: show more players to compare and border radius button

- frontend/src/components/Input/Input.jsx
- frontend/src/pages/Login.jsx
- frontend/src/sass/site-layout/_login-page.scss
> bug login page

- frontend/src/pages/LandingPage.jsx
> bug: Landing buttons

- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/index.jsx
- frontend/src/pages/ContactPlayer.jsx
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/sass/site-layout/_contact-player.scss
- frontend/src/sass/site-layout/_index.scss
[Ticket](https://trello.com/c/gKKasuiA/113-create-contact-player-page)
> Contact player page.
The styling is not done yet.
```
npm run
```
1. 
2.
---
> pr-feature-create-contact-player

- backend/src/routes/favorite.ts
- frontend/src/pages/FavoritesPage.jsx
Updated the favorite Redis cache to check if we have a favorite in the database in order to delete the cache
> bug: Favorites Page - Favorite deletion

- frontend/.env.example
- frontend/package-lock.json
- frontend/package.json
- frontend/src/hoc/withAuthentication.jsx
- frontend/src/pages/ContactPlayer.jsx
- frontend/src/sass/site-layout/_contact-player.scss
[Ticket](https://trello.com/c/gKKasuiA/113-create-contact-player-page)
> Contact player completed
```
npm install @emailjs/browser --save
```
1. 
2.
---
> fix: contact player completed

- frontend/package-lock.json
- frontend/src/components/ProfilePopUp/ProfilePopUp.jsx
- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/base-elements/_profile-popup.scss
- frontend/src/sass/style.scss
> feature: Create Logout Botton

- frontend/src/components/Footer/Footer.jsx
- frontend/src/index.jsx
- frontend/src/pages/ContactUs.jsx
- frontend/src/sass/site-layout/_contact-player.scss
[Ticket](https://trello.com/c/LJ157EFg/115-create-contact-us-page)
> Contact us page
```
npm run
```
1. 
2.
---
> pr-feature-create-contact-us-page

- frontend/src/components/Slider/Slider.jsx
- frontend/src/components/Tag/Tag.jsx
- frontend/src/pages/ComparisonPage.jsx
- frontend/src/pages/PlayerReviewOverview.jsx
- frontend/src/pages/ReviewPlayer.jsx
- frontend/src/sass/base-elements/_avatar.scss
- frontend/src/sass/base-elements/_slider.scss
- frontend/src/sass/site-layout/_comparison-page.scss
- frontend/src/sass/site-layout/_player-review.scss
- frontend/src/sass/site-layout/_top-players-page.scss
> bug: Fix Styling Review pages

- frontend/src/components/RadarChart/RadarChart.jsx
- frontend/src/pages/PlayerComparisonSelectPage.jsx
- frontend/src/pages/PlayerDetailsPage.jsx
- frontend/src/sass/site-layout/_player-details-page.scss
[Ticket](https://trello.com/c/vYhFVNCd/116-player-detail)
> Player details page CSS completed
```
npm run
```
1. 
2.
---
> fix: player details page css

- frontend/src/pages/ContactPlayer.jsx
- frontend/src/sass/site-layout/_contact-player.scss
[Ticket](https://github.com/zyzmoz/global-player/issues/384)
> Navigation menu fixed in contact player page.
Please remember paste the api key in the env file to be able to submit the contact forms
```
npm run
```
1. 
2.
---
> fix: navigation menu fixed in contact player page

- frontend/src/pages/LandingPage.jsx
[Ticket](https://trello.com/c/f3QEg9mQ/119-add-promo-video-to-landing-page)
> Youtube link added to landing page
```
npm run
```
1. 
2.
---
> fix: promo video added

- frontend/src/components/Sidebar/Sidebar.jsx
- frontend/src/pages/PlayerComparisonSelectPage.jsx
- frontend/src/sass/site-layout/_player-comparison-select-page.scss
[Ticket](https://trello.com/c/dcdeqXgl/117-player-comparasion-select-page)
> navigation menu and disabled/active buttons fixed.
change background color when adding players using "+ VS" button in progress
```
npm run
```
1. 
2.
---
> fix: player comparison select page improvement in progress

- frontend/src/pages/ContactPlayer.jsx
- frontend/src/pages/ContactUs.jsx
- frontend/src/sass/site-layout/_contact-player.scss
- frontend/src/sass/site-layout/_index.scss
[Ticket](https://trello.com/c/hKnBbgq0/120-fix-contact-pages)
> Contact pages completed
```
npm run
```
1. 
2.
---
> fix: contact pages completed

- frontend/src/pages/Login.jsx
> bug: Removed forgot password button

- frontend/src/sass/site-layout/_player-details-page.scss
[Ticket](https://trello.com/b/StCLAI8p/project-2-team-supernova)
```
npm run
```
1. 
2.
---
> fix: desktop view and CSS

- frontend/src/pages/LandingPage.jsx
- frontend/src/sass/site-layout/_index.scss
changing the icons of the table according to figma
```
npm run
```
1. 
2.
---
> bug: icons table landing page fix

- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/site-layout/_top-players-page.scss
- frontend/src/sass/tables/_tables.scss
> bug: Fixed scroll down icon and  search bar and table alignment

- frontend/src/components/Header/RecruitersPagesNavMenu.jsx
- frontend/src/sass/navigation/_header.scss
- frontend/src/sass/site-layout/_favorites-page.scss
- frontend/src/sass/site-layout/_player-comparison-select-page.scss
- frontend/src/sass/site-layout/_top-players-page.scss
> Bug: css dashboard & lack of logout on mobile dashboard

- frontend/src/pages/PlayerReviewOverview.jsx
- frontend/src/pages/ReviewPlayer.jsx
- frontend/src/sass/site-layout/_player-review.scss
> bug: Added Sidebar in review pages

- frontend/src/sass/site-layout/_contact-player.scss
- frontend/src/sass/site-layout/_favorites-page.scss
- frontend/src/sass/site-layout/_player-comparison-select-page.scss
- frontend/src/sass/site-layout/_player-details-page.scss
- frontend/src/sass/site-layout/_player-review.scss
[Ticket](https://trello.com/c/mGbtBY7j/122-fix-footer-in-multiple-pages)
> footer displayed only when sidebar is not visible
```
npm run
```
1. 
2.
---
> fix: footer displayed only when sidebar is not visible

- frontend/src/sass/site-layout/_top-players-page.scss
> bug-css-width-header-dashboard

- frontend/src/sass/site-layout/_plans-page.scss
> bug: Plans Page Mobile - Layout Basic

- frontend/src/sass/site-layout/_index.scss
> bug-background

- frontend/src/pages/ComparisonResultsPage.jsx
- frontend/src/pages/PlayerComparisonSelectPage.jsx
- frontend/src/pages/TopPlayersPage.jsx
- frontend/src/sass/base-elements/_line-chart.scss
- frontend/src/sass/site-layout/_comparison-page.scss
- frontend/src/sass/site-layout/_comparison-results-page.scss
- frontend/src/sass/site-layout/_top-players-page.scss
- frontend/src/sass/tables/_tables.scss
> bug: Fixed table radius and width on dashboard and comparison results

- frontend/src/pages/PlayerComparisonSelectPage.jsx
- frontend/src/sass/site-layout/_player-comparison-select-page.scss
[Ticket](https://trello.com/c/dcdeqXgl/117-player-comparasion-select-page)
> Player select player completed
```
npm run
```
1. 
2.
---
> fix: player select page completed
